bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key x kill-pane

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind p paste-buffer

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g default-terminal 'screen-256color'

set-option -g status-left-length 50
set-option -g status-right-length 80
set-option -g status-interval 1

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_empty_prompt 'tmux'
set -g @prefix_highlight_prefix_prompt 'wait'
set -g @prefix_highlight_copy_prompt 'copy'
set -g @prefix_highlight_sync_prompt 'sync'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_empty_has_affixes 'on' # default is 'off'
set -g @prefix_highlight_output_prefix ' <'
set -g @prefix_highlight_output_suffix '> '


set -g status-bg "#afff5f"

set -g @prefix_highlight_fg '#2d2a2e,bold'  # default is 'colour04'
set -g @prefix_highlight_bg '#87ffff'  # default is 'colour04'
set -g @prefix_highlight_copy_mode_attr 'fg=#2d2a2e,bg=#ffff87,bold' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_sync_mode_attr 'fg=#2d2a2e,bg=#af87ff,bold' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_empty_attr 'fg=#2d2a2e,bg=#afff5f,bold' # default is 'fg=default,bg=default'

set -g status-left '#{prefix_highlight} [#S] '
set -g status-right '#H %H:%M:%S %p '
# set -g status-right '#{prefix_highlight} #H %H:%M:%S %p '

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


