[colors.primary]
background= "0x2c2525"
foreground= "#f8f8f2"

[colors.normal]
black=   '0x2c2525'
red=     '0xfd6883'
green=   '0xadda78'
yellow=  '0xf9cc6c'
blue=    '0x70b0f3'
magenta= '0xeba8eb'
cyan=    '0x85dacc'
white=   '0xfff1f3'

[colors.bright]
black=   '0x72696a'
red=     '0xfd6883'
green=   '0xadda78'
yellow=  '0xf9cc6c'
blue=    '0x70b0f3'
magenta= '0xa8a9eb'
cyan=    '0x85dacc'
white=   '0xfff1f3'

[font]
size = 13

[font.normal]
family = "DejaVuSansM Nerd Font"

[window]
opacity = 1.00
decorations = "Buttonless"
